### PR TITLE
Fix Android crash related to bitmaps cleanup in MvxImageCache

### PR DESCRIPTION
**Pull request by alexshikov**
Fix to https://github.com/MvvmCross/MvvmCross-Plugins/issues/41
- Use ImmutableDictionary to synchronise operations on entries
- Dispose images on MainThread

### CODE REVIEW

**Comment by alexshikov** [comment]
This PR also fixes https://github.com/MvvmCross/MvvmCross-Plugins/issues/31

**Comment by roubachof** [comment]
I'm not sure if Interlocked.Exchange is needed:
Assignement is atomic in C#, and since we don't use the return value of Interlocked.Exchange, I don't really see the point of using it.

**Comment by alexshikov** [comment]
@roubachof you actually right, I also thought about it after PR merged...

**Comment by Cheesebaron** [comment]
Please continue this in #75 

Basically make a new PR which fixes this :)

**Pull request merged**
