### PR TITLE
Implement Fused location plugin for Android

### PR DESCRIPTION
**Pull request by alexshikov**
Initial implementation of Fused Location Provider #84. See:
- https://developer.android.com/training/location/retrieve-current.html
- http://www.tothenew.com/blog/googles-fused-location-api-for-android/

**ToDo**
- [x] Add project to the solution (I use only XS and it modifies all csproj files)
- [x] Setup nuspec
- [x] Load plugin on startup (plugin name doesn't fit lookup convention)

**Bootstrap issue**
Plugin has the name MvvmCross.Plugins.Location.Fused.Droid (note **Fused** before **Droid**). Plugin loader fails with lookup of MvvmCross.Plugins.Location.Droid. How to solve it? Emit **Fused** in the namespace/DLL? Modify plugin loader to support the case MvvmCross.Plugins.PluginName.**Stuff**.Droid?

### CODE REVIEW

**Comment by martijn00** [comment]
About the naming issue: why not name it something like `MvvmCross.Plugins.FusedLocation.Droid`?

**Comment by pocheshire** [comment]
`IGoogleApiClient` in `FusedLocationHandler`? Maybe `GoogleApiClient`?

`IGoogleApiClientConnectionCallbacks` and `IGoogleApiClientOnConnectionFailedListener`  should be replaced to `GoogleApiClient.IConnectionCallbacks` and `GoogleApiClient.IOnConnectionFailedListener`.

No `GoogleApiClientBuilder` but `GoogleApiClient.Builder`

**Comment by pocheshire** [comment]
And what about check installed Google Play Services or not?

```sharp
private bool IsGooglePlayServicesInstalled()
{
        int queryResult = GoogleApiAvailability.Instance.IsGooglePlayServicesAvailable (Context);
        if (queryResult == ConnectionResult.Success)
        {
            Mvx.Resolve<IMvxTrace>().Trace(MvxTraceLevel.Diagnostic,  "", () => "Google Play Services is installed on this device.");
            return true;
        }

        if (GoogleApiAvailability.Instance.IsUserResolvableError (queryResult))
        {
            string errorString = GoogleApiAvailability.Instance.GetErrorString (queryResult);
            throw new MvxException(string.Format("There is a problem with Google Play Services on this device: {0} - {1}", queryResult, errorString));
        }

        return false;
}
```

**Comment by alexshikov** [comment]
@pocheshire there are no such classes and interfaces as you proposed. The ones used in the code are correct.

**Comment by pocheshire** [comment]
@SeeD-Seifer see [this](https://github.com/xamarin/monodroid-samples/tree/master/FusedLocationProvider) sample

**Comment by thefex** [comment]
@pocheshire @SeeD-Seifer Seed-Sefier is right. There were class changes in some google location update and Seed-Seifer uses most recent now.

**Comment by alexshikov** [comment]
@thefex @pocheshire Thanks. The difference is because in the sample used GooglePlayServices 29.0.0.1 and in the plugin 25.0.0.0

Does it make sense to migrate to the latest packages?
Does it make sense to increase SDK build version from 5.0 to 6.0?

**Comment by Cheesebaron** [comment]
It is ok if you upgrade the packages and SDK build version.

**Comment by alexshikov** [comment]
**Issue 1**
GoogleClientApi crashes when started from non _OnCreated_ method http://stackoverflow.com/questions/29343922/googleapiclient-is-throwing-googleapiclient-is-not-connected-yet-after-onconne

**Solutions**
1. Return specific error that describes an issue and propose _developer_ to start IMvxLocationService from `OnCreate()` method (either Activity/Fragment or custom Service).
2. Wrap GoogleClientApi handling into Android background service as described here https://developer.xamarin.com/guides/android/application_fundamentals/backgrounding/part_3_android_backgrounding_walkthrough/

---

**Issue 2**
There is no option to provide alternative plugin implementations.

**Description**
Plugin renaming does not affect the result of the issue. Either `FusedLocation.Droid` or `Location.Fused.Droid` it is not clear how to prepare nuget package that uses `MvvmCross.Plugins.Location` package as PCL, but loads `MvvmCross.Plugins.FusedLocation.Droid` for Droid project. (NOTE: iOS project should use Location + Location.iOS at the same time).
If FusedLocation plugin going to depend on `MvvmCross.Plugins.Location` nuget package, then old `MvvmCross.Plugins.Location.Droid` library is loaded.

---

**Issue 3**
There is no option to load plugins with custom names (which does not fit convention)

**Description**
iOS plugin loader based on explicit platform type specification: https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Platform/Platform/Plugins/MvxLoaderPluginBootstrapAction.cs#L41

In oposite, Android loads plugins based on PCL namespace: https://github.com/MvvmCross/MvvmCross/blob/4.0/MvvmCross/Platform/Platform/Plugins/MvxFilePluginManager.cs#L81

**Solutions**
1. Implement `MixedPluginManager` that could support both by-convention and explicit platform plugin specification.
2. Embed unique plugin loading into Bootstrap file
3. Simply prepare good description how to update Setup with custom plugin implementations: https://gist.github.com/SeeD-Seifer/fb8cf3da04c229e0f18faa4476731aa5

**Comment by alexshikov** [comment]
https://github.com/MvvmCross/MvvmCross/pull/1290 is a solution for Issue 3

**Comment by alexshikov** [comment]
Have no idea how to fix **Issue 2**.
How to build two different NuGet packages for Android platform sharing the same Portable code without referencing it as NuGet dependency?

**Comment by alexshikov** [comment]
**Issue 1** appeared related to testing code issue, rather then GoogleClientApi itself.

The issue happened when location watcher stopped inside **OnSuccess** callback. This is fixed by previous commit.

So now the only issue left - how to distribute Fused NuGet package?

**Comment by alexshikov** [comment]
Alright guys, everything is pretty ready for the plugin to be shipped. Except...

**How to distribute this as NuGet package?**

**Comment by martijn00** [comment]
We can add a nuspec to get this up as Nuget

**Comment by alexshikov** [comment]
This is the only idea I have on nuspec https://gist.github.com/SeeD-Seifer/748e9e60c89d7fa73b35d33c6ea8da6e

**Comment by martijn00** [comment]
I was just creating that one, can you make a PR? We are about to make a new release, so we could add this then.

**Comment by alexshikov** [comment]
Of course.

**Comment by alexshikov** [comment]
Done https://github.com/MvvmCross/MvvmCross-Plugins/pull/97

**Pull request merged**
