### PR TITLE
Preserve attribute

### PR DESCRIPTION
**Pull request by heytherewill**
Like I said on mvvmcross/mvvmcross#1432, the Plugins would benefit a lot more from the PreserveAttribute.

I made a test on one of my projects, using the aggressive linker setting and removing the "Ignore Assemblies" string that protected MvvmCross assemblies. The results:
- The Core MvvmCross assemblies had no problem at all. They just worked
- The plugins crashed. In order to fix it, I had to add the `PreserveAttribute` to every single `Plugin` and `PluginLoader`
- The FilePlugin was still crashing, so I had to `Preserve` it as well
- The VisibilityPlugin didn't work even though it didn't crash, hence why it's fixed

From here, I see three different paths:

1 - We'll `Preserve` all crucial plugin features to prevent Crashes/Unexpected behaviours. This assumes that users that include the plugin will always use it. This is my preferred course of action.
2 - We'll just `Preserve` classes that cause crashes and users will manually have to `LinkerPleaseInclude` the hell out of the plugins they use.
3 - We'll just `Preserve` `Plugins` and `PluginLoaders` and users will have to deal with Crashes/Unexpected behaviours.

I just need to know which option is the best in order to continue the work on this :)

### CODE REVIEW

**Comment by martijn00** [comment]
I would go for option 1. I think it's a good thing to help the users with this.

**Comment by kjeremy** [comment]
Option 1 is completely reasonable.  This LGTM :+1:

**Comment by Cheesebaron** [comment]
Would have loved more descriptive commit messages instead of just "Fix x"

I vote that we squash this PR before it gets merged.

**Comment by kjeremy** [comment]
Definitely squash this.

**Comment by heytherewill** [comment]
There's really nothing else to describe, I just added the `Preserve` attribute. I just split stuff into different commits because it made it easier to rollback.

**Comment by Cheesebaron** [comment]
Fix x does not describe that a preserve attribute was added. I only describes that something was fixed...

Doesn't matter, we will squash this :)

**Pull request merged**
