### PR TITLE
MakeRequestForAsync always returns an MvxDecodedRestResponse, even if…

### PR DESCRIPTION
**Pull request by xBoogieManx**
… the stream was unattanable. In this case the StatusCode = BadRequest.

MakeStreamRequestAsync and MakeRequestAsync use ProcessExceptionResponse which builds a MvxDecodedRestResponse with StatusCode = BadRequest

ProcessExceptionResponse could set the StatusCode based on what the exception

### CODE REVIEW

**Comment by martijn00** [comment]
This looks like an improvement 👍 Does it break anything and is it tested?

**Comment by xBoogieManx** [comment]
No, it does not break anything.
Yes, I have tested it:

var url1 = BooksService.GetSearchUrl("MonoTouch");
var url2 = "https://Fictitious.com";
var json = new MvvmCross.Plugins.Json.MvxJsonConverter();
var client = new MvvmCross.Plugins.Network.Rest.MvxJsonRestClient
{
    JsonConverterProvider = () => json
};
var request = new MvxRestRequest(url1);
MvxDecodedRestResponse<BookSearchResult> theResponse = null;
Exception exception = null;
theResponse = await client.MakeRequestForAsync<BookSearchResult>(request);
if(theResponse.StatusCode == HttpStatusCode.BadRequest)
{ // something went wrong - such as url2 was called }
else
{ // all is good }

Future Potential Improvements:
The ProcessExceptionResponse methods could set the StatusCode based on the Exception instead of simply setting BadRequest. If this is done, then MakeRequestForAsync will have to take this into account.

**Comment by Cheesebaron** [comment]
It doesn't compile here on Mac.

MvxRestClient line 143, ambigious reference to ProcessExceptionResponse

**Comment by xBoogieManx** [comment]
I did add the two ProcessExceptionResponse methods:

`ProcessExceptionResponse(MvxRestRequest restRequest, Exception ex, Action<MvxStreamRestResponse> continueAction)`
And 
`ProcessExceptionResponse(MvxRestRequest restRequest, Exception ex, Action<MvxRestResponse> continueAction)`

The continueAction parameters distinguish between the two.

If Mac had an issue with method overload then why does the master branch compile on a Mac when the master branch currently has the two ProcessResponse methods that are distinguishable by their signatures ... and the distinction is in the same manner as ProcessExceptionResponse?

`ProcessResponse(MvxRestRequest restRequest, HttpWebRequest httpRequest, Action<MvxRestResponse> successAction, Action<Exception> errorAction)`
And
`ProcessResponse(MvxRestRequest restRequest, HttpWebRequest httpRequest, Action<MvxStreamRestResponse> successAction, Action<Exception> errorAction)`

Can someone who is more familiar with the nuances of a Mac take a look at the code and at least point me in the right direction please.

**Comment by xBoogieManx** [comment]
I updated the pull request.

I  renamed:
`ProcessExceptionResponse(MvxRestRequest restRequest, Exception ex, Action<MvxStreamRestResponse> continueAction)`

To

`ProcessStreamExceptionResponse(MvxRestRequest restRequest, Exception ex, Action<MvxStreamRestResponse> continueAction)`

Please let me know if this compiles on Mac

**Comment by xBoogieManx** [comment]
Can someone plz compile my last pull request on a Mac so I know if renaming the one method fixed the ambiguity issue.

Thank you.

**Comment by martijn00** [comment]
Seems to work fine on Mac!

**Pull request merged**
