### PR TITLE
Add a param named 'allowsEditing' for TakePicture or ChoosePictureFromLibrary. 

### PR DESCRIPTION
**Pull request by ZhangZihe**
Add a param named 'allowsEditing' for TakePicture or ChoosePictureFromLibrary. But my account doesn't support windows phone, so I just implement those on iOS and Android. I wish someone help me to implement other platforms.

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Could you please describe in more detail what this Pull Request does?

It does not _just_ add a `allowsEditing` bool.

**Comment by ZhangZihe** [comment]
@Cheesebaron Just add some overload method to support crop a picture with a 'allowsEditing' param when take a picture or choose a picture from a library.

**Comment by Cheesebaron** [comment]
As I said, the code in the PR seems to do more than just that.

It adds intent flags and data when `allowsEditing` is set. Maybe this should be passed into the method instead of static inside of it?

**Comment by ZhangZihe** [comment]
@Cheesebaron I add a constant named of 'RESULT_CAMERA_CROP_PATH_RESULT' as the resultCode of a intent named of 'com.android.camera.action.CROP', such as 'MvxIntentRequestCode.PickFromFile'. The intent provide a function and UI to crop picture. It necessary to be define with 'static'.

**Comment by ZhangZihe** [comment]
@Cheesebaron  Please consult the article http://blog.csdn.net/wk843620202/article/details/51429552. But it is wrote by Chinese.

**Comment by Cheesebaron** [comment]
The URL doesn't seem to load unless you go through Google Translate or similar, just times out. Anyways the translated blog article does not explain much, other than it is launching a crop intent if present on the Android device.

So there are several problems with this PR:
1. No options to choose the parameters yourself for the crop intent
2. The Crop intent is not present on all Android devices and may throw and exception or not launch at all

**Comment by ZhangZihe** [comment]
@Cheesebaron I see, I will try to fix my solution.

**Pull request closed without merging**
