### PR TITLE
Ability to resolve the download cache so that we can clear the cache

### PR DESCRIPTION
**Pull request by promontis**
I was trying to clear the image cache, but there is no good way to resolve the interface where that is implemented. This PR will allow provide that.

### CODE REVIEW

**Comment by promontis** [comment]
@martijn00 can you have a look?

**Comment by Cheesebaron** [comment]
Looks OK to me. I guess the change here is that you `IMvxFileDownloadCache`, which didn't happen before.

**Comment by promontis** [comment]
Jup, otherwise there is no easy way to clear the cache

**Comment by promontis** [comment]
Thnx for merging @Cheesebaron

**Pull request merged**
