### PR TITLE
Allow to get the selected image Display Name if existing.

### PR DESCRIPTION
**Pull request by Didux**
In some case user could need the selected file display name.
It's a little method addition who allow to use a PictureAvailable action with the file name in parameter.

### CODE REVIEW

**Comment by martijn00** [comment]
Can you resolve the conflicts?

**Comment by Didux** [comment]
Yes i can.

**Comment by Didux** [comment]
Done :)

**Comment by martijn00** [comment]
Hmm it seems this is a bit mixed up. You have a lot of changes this way, and we can't see what really changed. Could you create a new branch at your own fork, and add the changes to that and make a PR? That way it would be clear what this is.

**Pull request closed without merging**
